# Run tests for this project

name: Test

on: [workflow_dispatch]
#  push:
#    branches: [ trunk ]
#  pull_request:
#    branches: [ trunk ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    # Runs a single command using the runners shell
    - name: Run all tests
      run: go test
